### ISSUE TITLE
Make input manager start on any scene load

### ISSUE THREAD

**Issue by ashleyjlive** [rebelrabbit/UnityInputManager#1]
Solution: 
Create a new script called Entry and then put this code in. Remove any instances of input manager in all scenes. This script ensures that the input manager instance always exists regardless of what scene.

```
public static class Entry
{
[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
public static void OnLoad()
{
GameObject obj = new GameObject("Input Manager", typeof(InputManager ));
GameObject.DontDestroyOnLoad(obj);
}
}

```

**Comment by gontzalve** [comment]
Thank you! Noted!
